language: node_js
node_js:
- "stable"
install:
  - npm install
  - npm install -g db-migrate
script:
  - npm test
  - npm run coverage
services:
- postgresql
env:
- NODE_ENV=test DB_USERNAME=enjames DB_PASSWORD=password DB_NAME=beconnect
before_script:
- psql -c 'create database beconnect;' -U postgres
- psql -c "CREATE USER enjames WITH PASSWORD 'password';" -U postgres
- db:migrate
cache:
  directories:
    - "node_modules"
addons:
    code_climate:
        repo_token: 3c4c5bcf7133b8da52081439a723e74adedc1a685cf64364eac9ff05e807a4ee
after_success :
    - npm run coverage
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
